[git]
skip_preview = true
skip_emojis = true

[[scopes]]
name = "rust"
description = "The rust core library related"

[[scopes]]
name = "leptos"
description = "The leptos components related"

[[scopes]]
name = "react"
description = "The react components related"
