mod alert;
mod arrow_down;
mod arrow_left;
mod arrow_right;
mod arrow_up;
mod book;
mod close;
mod discord;
mod ferris;
mod file;
mod filter;
mod github;
mod link;
mod linkedin;
mod location;
mod menu;
mod moon;
mod project;
mod roadmap;
mod search;
mod share;
mod star_bold;
mod sun_line;
mod telegram;
mod twitter;
mod youtube;

pub use alert::*;
pub use arrow_down::*;
pub use arrow_left::*;
pub use arrow_right::*;
pub use arrow_up::*;
pub use book::*;
pub use close::*;
pub use discord::*;
pub use ferris::*;
pub use file::*;
pub use filter::*;
pub use github::*;
pub use link::*;
pub use linkedin::*;
pub use location::*;
pub use menu::*;
pub use moon::*;
pub use project::*;
pub use roadmap::*;
pub use search::*;
pub use share::*;
pub use star_bold::*;
pub use sun_line::*;
pub use telegram::*;
pub use twitter::*;
pub use youtube::*;
